version: '3'

services:
  db:
    build: ./db 
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
  spgm:
    build: ./spgm
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      DATABASE_USER: spgm
      DATABASE_PASSWORD: spgm
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    command: bash -c "rm -f /spgm/tmp/pids/* && sleep 10 && bundle exec rails db:migrate && sleep 30 && bundle exec rails s -b 0.0.0.0"

